# Generated by Django 4.0.5 on 2022-06-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appmain.cliente')),
                ('razon_social', models.CharField(default='None', max_length=50)),
                ('contacto', models.CharField(default='None', max_length=50)),
            ],
            bases=('appmain.cliente',),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
